### ISSUE TITLE
Python 3.7.0 breaks older version of LDAP3 module

### ISSUE THREAD

**Issue by ghost** [ualibraries/patron-groups#11]
E.g.:

```
% python setup.py sdist
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from src.petal import __version__
  File "/Users/mgsimpson/Desktop/Projects/ual-patron-groups/src/main/python/src/petal/__init__.py", line 3, in <module>
    from .ldap_query import LDAPQuery
  File "/Users/mgsimpson/Desktop/Projects/ual-patron-groups/src/main/python/src/petal/ldap_query.py", line 1, in <module>
    import ldap3
  File "/Users/mgsimpson/.pyenv/versions/ual-patron-groups/lib/python3.7/site-packages/ldap3/__init__.py", line 132, in <module>
    from .core.connection import Connection
  File "/Users/mgsimpson/.pyenv/versions/ual-patron-groups/lib/python3.7/site-packages/ldap3/core/connection.py", line 55
    from ..strategy.async import AsyncStrategy
                        ^
SyntaxError: invalid syntax
```

Quick Google search shows that we'll need to bump the version number in requirements.txt for LDAP3 if we want this to run under Python 3.7.0+. Probably good to just do a branch where we update versions on all dependencies just for good measure.

**Comment by ghost** [comment]
This got fixed in one of the intervening releases where I bumped a bunch of dependency versions.
